[package]
name = "egg_halides_trs"
version = "0.1.0"
authors = ["Smail KOURTA <gs_kourta@esi.dz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egg = "0.6.0"
ordered-float = "1"
env_logger = "0.8.2"
colored = "2"
